version: "2"
run:
  go: "1.25"
linters:
  enable:
    - gosec
    - misspell
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - govet
    - revive
    - goconst
    - gocritic
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
